# Generated by Django 4.0.5 on 2022-06-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_bot_name', models.CharField(max_length=100)),
                ('chat_bot_id', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=50)),
                ('chat_from', models.CharField(default='bot', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='wellcome_msg',
            field=models.CharField(default='Hi, welcome to this chatbot', max_length=510),
        ),
    ]
