# Generated by Django 4.0.5 on 2022-06-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_chat_room_wellcome_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bot_id',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
