# Generated by Django 4.0.5 on 2022-06-28 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_bot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_bot_name',
            new_name='chat_room',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='chat_from',
            new_name='message_from',
        ),
    ]
