# Generated by Django 4.0.5 on 2022-06-28 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_rename_chat_bot_name_chat_chat_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_bot_id',
        ),
    ]
