# Generated by Django 4.0.5 on 2022-06-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_chat_chat_bot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Answers',
            field=models.TextField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='Questions',
            field=models.TextField(default='None', max_length=50),
        ),
    ]
