# Generated by Django 4.0.5 on 2022-06-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_room_answers_room_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Answers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='Questions',
            field=models.TextField(),
        ),
    ]
